# Generated by Django 5.0.6 on 2024-05-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TNP_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
