# Generated by Django 5.0.6 on 2024-05-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TNP_app', '0002_customer_delivery_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_item',
            field=models.ManyToManyField(through='TNP_app.OrderItem', to='TNP_app.food'),
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TNP_app.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TNP_app.food')),
            ],
        ),
    ]
