# Generated by Django 5.0.6 on 2024-05-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TNP_app', '0004_rename_food_type_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='title',
        ),
    ]
