# Generated by Django 5.0.6 on 2024-07-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TNP_app', '0006_alter_customerreview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.PositiveIntegerField(verbose_name=0),
        ),
    ]
